#!/bin/bash

print_help() {
    echo -e "  \e[3mA small script to make dev life better\e[0m"
    echo "  USAGE: ipm [COMMAND]"
    echo ""
    echo "  COMMAND:  fe:dev          Run FE dev"
    echo "            fe:build        Build FE"
    echo "            fe:install      Install FE dependencies"
    echo "            be:run          Run"
    echo "            be:dev          Run and hot reload"
    echo "            mg:new <name>   Make new migration"
    echo "            mg:remove       Remove migration"
    echo "            db:update       Update database"
    echo "            db:drop         Drop database"
    echo "            dk:run          Docker run (not available now)"
}

main() {
    case "$1" in
        -h|--help)
            print_help
            ;;
        "fe:install")
            echo "npm --prefix ./src/IPM.ClientApp install"
            npm --prefix ./src/IPM.ClientApp install
            ;;
        "fe:dev")
            echo "npm --prefix ./src/IPM.ClientApp run dev"
            npm --prefix ./src/IPM.ClientApp run dev
            ;;
        "fe:build")
            echo "npm --prefix ./src/IPM.ClientApp run build"
            echo "rm  -rf ./src/IPM.WebApi/Views/Home/Index.cshtml"
            echo "mv ./src/IPM.WebApi/wwwroot/Index.cshtml ./src/IPM.WebApi/Views/Home/"
            npm --prefix ./src/IPM.ClientApp run build && \
                rm  -rf ./src/IPM.WebApi/Views/Home/Index.cshtml && \
                mv ./src/IPM.WebApi/wwwroot/Index.cshtml ./src/IPM.WebApi/Views/Home/
            ;;
        "db:update")
            echo "dotnet ef database update --project src/IPM.Infrastructure --startup-project src/IPM.WebApi"
            dotnet ef database update --project src/IPM.Infrastructure --startup-project src/IPM.WebApi
            ;;
        "db:drop")
            echo "dotnet ef database drop --project src/IPM.Infrastructure --startup-project src/IPM.WebApi"
            dotnet ef database drop --project src/IPM.Infrastructure --startup-project src/IPM.WebApi
            ;;
        "mg:remove")
            echo "dotnet ef migrations remove --project src/IPM.Infrastructure --startup-project src/IPM.WebApi"
            dotnet ef migrations remove --project src/IPM.Infrastructure --startup-project src/IPM.WebApi
            ;;
        "mg:new")
            shift
            migration_name="NewMigration"
            if [[ $# != 0 ]]; then
                migration_name="$1"
            fi
            echo "dotnet ef migrations add $migration_name --project src/IPM.Infrastructure --startup-project src/IPM.WebApi"
            dotnet ef migrations add "$migration_name" --project src/IPM.Infrastructure --startup-project src/IPM.WebApi
            ;;
        "be:run")
            echo "dotnet run --project src/IPM.WebApi"
            dotnet run --project src/IPM.WebApi
            ;;
        "be:dev")
            echo "dotnet watch --project src/IPM.WebApi"
            dotnet watch --project src/IPM.WebApi
            ;;
        *)
            echo "Command not found: $1"
            print_help
            ;;
    esac
}

main "$@"
